### ISSUE TITLE
没有匹配[json]类型的转换器！

### ISSUE THREAD

**Issue by southfly** [ejlchina/okhttps#18]
**Describe the bug**
```
Exception in thread "main" com.ejlchina.okhttps.internal.HttpException: 没有匹配[json]类型的转换器！
	at com.ejlchina.okhttps.internal.TaskExecutor.doMsgConvert(TaskExecutor.java:145)
	at com.ejlchina.okhttps.HttpTask.toRequestBody(HttpTask.java:699)
	at com.ejlchina.okhttps.HttpTask.buildRequestBody(HttpTask.java:689)
	at com.ejlchina.okhttps.HttpTask.prepareRequest(HttpTask.java:596)
	at com.ejlchina.okhttps.HttpTask.prepareCall(HttpTask.java:585)
	at com.ejlchina.okhttps.internal.AsyncHttpTask.lambda$request$0(AsyncHttpTask.java:263)
	at com.ejlchina.okhttps.internal.HttpClient.preprocess(HttpClient.java:184)
	at com.ejlchina.okhttps.internal.AsyncHttpTask.request(AsyncHttpTask.java:255)
	at com.ejlchina.okhttps.internal.AsyncHttpTask.post(AsyncHttpTask.java:217)
	at com.hellosouth.file_transfer.utils.OkHttpUtils.main(OkHttpUtils.java:231)

```
**To Reproduce**
```
  Map<String, Object> map = new HashMap<>();
        map.put("uploadId", "uploadId");
//        map.put("base64",base64);
        map.put("total", 10);
        map.put("current", 2);
        HTTP http = HTTP.builder().bodyType(OkHttps.JSON).build();
        http.async(UPLOAD_URL)
                .bodyType(OkHttps.JSON)
                .addBodyPara(map)
//                .setBodyPara(map)
                .setOnException((IOException e) -> {
                    // 异常回调
                    e.printStackTrace();
                })
                .setOnResponse((HttpResult res) -> {

                    // 响应回调
                    int status = res.getStatus();       // 状态码
                    Headers headers = res.getHeaders(); // 响应头
                    HttpResult.Body body = res.getBody();          // 报文体
                    System.out.println(body);

                })
                .post();
```

```
  <!-- okhttps -->
        <dependency>
            <groupId>com.ejlchina</groupId>
            <artifactId>okhttps</artifactId>
            <version>2.4.2</version>
        </dependency>
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ejlchina** [comment]
当出现这个异常是，一般是让 OkHttps 去自动解析 JSON 却没有给它配置`MsgConvertor`导致的，当遇到这个异常是，可按如下步骤检查：

**1、** 项目依赖中是否添加了 json 扩展包：`okhttps-fastjson`、`okhttps-gson`、`okhttps-jackson`，添加一个即可

**2、** 发起请求时，使用的是 OkHttps 提供的工具类（`OkHttps`或`HttpUtils`）还是 自己构建的`HTTP`实例，如果是前者，框架会自动配置`MsgConvertor`，若是后者，得自己手动配置`MsgConvertor`：

```java
HTTP http = HTTP.builder()
    .addMsgConvertor(new FastjsonMsgConvertor());   // okhttps-gson
    .addMsgConvertor(new GsonMsgConvertor());       // okhttps-fastjson
    .addMsgConvertor(new JacksonMsgConvertor());    // okhttps-jackson
    .build();
```

**3、** 项目依赖中已经添加了 json 扩展包，并且使用的是 OkHttps 提供的工具类（`OkHttps`或`HttpUtils`），但还是有这个异常，这个时候一般是 IDE 的编译器的 BUG 导致的，请 clean 一下项目，重新运行即可。
