### ISSUE TITLE
在接入Stomp后，如果app网络断开，App直接奔溃,加try-catch也还是奔溃

### ISSUE THREAD

**Issue by yk007** [ejlchina/okhttps#26]
com.ejlchina.okhttps.internal.HttpException: WebSockt 连接异常: ws://192.168.101.233:10002/api/ws/websocket
        at com.ejlchina.okhttps.internal.WebSocketTask$MessageListener.onFailure(WebSocketTask.java:252)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onFailure(RealWebSocket.java:216)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: java.net.ConnectException: Failed to connect to /192.168.101.233:10002

**Comment by yk007** [comment]
@Override
		public void onFailure(okhttp3.WebSocket webSocket, Throwable t, Response response) {
			IOException e = t instanceof IOException ? (IOException) t : new IOException(t.getMessage(), t);
			doOnClose(toState(e), 0, t.getMessage());
			TaskListener<IOException> listener = httpClient.executor.getExceptionListener();
			if (listener != null) {
				if (listener.listen(WebSocketTask.this,  e) && onException != null) {
					execute(() -> onException.on(this.webSocket,  t), exceptionOnIO);
				}
			} else if (onException != null) {
				execute(() -> onException.on(this.webSocket,  t), exceptionOnIO);
			} else if (!nothrow) {
				throw new HttpException("WebSockt 连接异常: " + getUrl(), t);
			}
		}

发现异常是在这里抛出的

**Comment by ejlchina** [comment]
设置 `setOnException` 异常回调即可，或者使用 [全局异常监听](https://okhttps.ejlchina.com/v3/configuration.html#%E5%85%A8%E5%B1%80%E5%9B%9E%E8%B0%83%E7%9B%91%E5%90%AC) 也行。

**Comment by yk007** [comment]
非常感谢，问题已解决
